### ISSUE TITLE
Custom Updates Server vs EAS plan limits

### ISSUE THREAD

**Issue by murat0** [expo/custom-expo-updates-server#23]
Hi all, 

If we were to use a custom updates serer, how much of EAS cloud services do we still make use of behind the scenes? If any, do EAS plan limits still apply?

Thank you in advance

**Comment by nikhilonecode** [comment]
@murat0 I guess none.

**Comment by saxenanickk** [comment]
@murat0 I guess none.

**Comment by wschurman** [comment]
Can still use all EAS cloud services, even if not using EAS Update.
