### ISSUE TITLE
fs.stat().birthtime is unreliable

### ISSUE THREAD

**Issue by j005u** [expo/custom-expo-updates-server#24]
Hi there,

On my WSL2 development setup, for whatever reason fs.stat().birthtimeMs returns 0 and therefore .birthtime is incorrect (but truthy).

I found that using .ctime instead works fine. I also considered doing `new Date(parseInt(path.basename(updateBundlePath), 10)
1000).toISOString()` instead as this would more closely match how the latest update gets picked, however not everyone may use the exact timestamp format (s vs ms) for the folder name, so that might blow up.

Happy to send a PR if appropriate.

**Comment by cmdshepard** [comment]
+1 - I also had an issue with this on GCP App Engine. I refactored it to use the folder name.

**Comment by wschurman** [comment]
@j005u a PR would be awesome!
