### ISSUE TITLE
After updating the Android application using npx expo run:android in SDK 49, the client is unable to make update requests.

### ISSUE THREAD

**Issue by wennjie** [expo/custom-expo-updates-server#33]
After updating the Android application using "npx expo run:android" in SDK 49, the client is unable to make update requests.

sdkVersion:49.0.0

delete old android files  then run "npx expo run:android" get new android files , then  build with Androd-Studio , release apk cant request the updateurl

**Comment by Giasinit** [comment]
Did i solve the problem? could you specify?
