### ISSUE TITLE
Eas update custom URL

### ISSUE THREAD

**Issue by FrancoOrtiz** [expo/custom-expo-updates-server#34]
I created my custom server and generated my private and public keys using an OpenSSL command. In my client, I added the folder with the certificate.pem file to the root directory, this file contains the same public key as the server.

Then, in my app.config.js, I added the 'updates' property with the server URL, the codeSigningCertificate and codeSigningMetaData. 

Once that was done, I generated the Android and iOS files using `APP_TYPE=myApp npx expo prebuild`. For those, I followed this configuration process: https://github.com/expo/fyi/blob/main/eas-update-config.md#native-configuration. I have modified AndroidManifest.xml and Expo.plist with my update url and runtime version.

I performed an 'eas build' for the release version app, and then I executed the `APP_TYPE=myApp eas update` command with channel, version and platform specified.

eas update command return this error:

```
{
  "updates": {
    "url": "https://u.expo.dev/MY-PROJECT-ID"
  }
}

The native config files Expo.plist & AndroidManifest.xml must be updated to support EAS Update. Learn more: https://expo.fyi/eas-update-config.md#native-configuration

Cannot automatically write to dynamic config at: app.config.js
    Error: update command failed.
```

I had already set the URL in my app.config.js, but it's not the one that the error is asking for. If I use that one, it works, but I want the URL to be from my custom server. How can I solve this?

**Comment by wschurman** [comment]
EAS Update is a hosted service, independent of this repo. See the readme for more details.
