### ISSUE TITLE
Work well in localhost but not work when deploy to custom server

### ISSUE THREAD

**Issue by munawarkholil** [expo/custom-expo-updates-server#37]
I have cloned this repo, built the app with the updated URL pointing to localhost, and everything worked fine. However, when I deployed it to the server and rebuilt it with the same URL, in my case, I deployed it to Vercel, the Updates.checkForUpdateAsync() function always returns isAvailable=false

I logged it with flipper to see what happened and didn't find any errors

**Comment by arasrezaei** [comment]
I get isAvailable = false with `resean: updateRejectedBySelectionPolicy`

**Comment by arasrezaei** [comment]
@wschurman

**Comment by munawarkholil** [comment]
solved with https://github.com/expo/custom-expo-updates-server/issues/24#issue-1577953267
