### ISSUE TITLE
Http Respond as application/expo+json and application/json

### ISSUE THREAD

**Issue by Ddv0623** [expo/custom-expo-updates-server#38]
Hi,
I am currently working on create a .NET Core server to serve the expo updates.
In the example here I see that it always responded with content-type: multipart/mixed. while in the specification it is allowed to responded as application/expo+json and application/json.
Could you guys update the example here to show us how to implement it correctly?
Also I see that npm expo-updates is release version 0.23.0 with tag next?
Will there be any breaking change in the server side to support newer version of expo-updates

**Comment by wschurman** [comment]
This repo used to be application/json. Might be able to go back a ways in the history to see how it was implemented.
