### ISSUE TITLE
fabric error when building ios

### ISSUE THREAD

**Issue by FedeRBeije** [expo/custom-expo-updates-server#41]
Hi, i' copied your repo to try it and i'm following the readme file. When i have to build  i get this error.

error: Build input file cannot be found: 'custom-expo-updates-server/expo-updates-client/node_modules/react-native/React/Fabric/RCTThirdPartyFabricComponentsProvider.mm'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'React-RCTFabric' from project 'Pods'

and the build failed.

Do you have any suggestions about this? 

Thank you

**Comment by wschurman** [comment]
This has been updated to use continuous native generation. Try again with the latest code and hopefully that should fix it!
