### ISSUE TITLE
Warning: Max serverless function size of 50 MB compressed or 250 MB uncompressed reached

### ISSUE THREAD

**Issue by denniske** [expo/custom-expo-updates-server#42]
When deploying on vercel I get the following warning:

<img width="902" alt="image" src="https://github.com/expo/custom-expo-updates-server/assets/1076211/472454d5-ab3e-4572-be1a-1024885492b0">

I also get the following error when trying to download an update:

**API response for /api/assets?runtimeVersion=84.0.0&platform=ios&asset=...873.hbc exceeds 4MB**.
API Routes are meant to respond quickly. 
https://nextjs.org/docs/messages/api-routes-response-size-limit

Are there other platforms that are suited better for deploy a custom expo updates server?

**Comment by giautm** [comment]
I think you should use an external service to storage updates, like S3. It also reduce the size of response payload.

**Comment by denniske** [comment]
Thank you! I am uploading the files to S3 now and put the link to a connected CDN into the manifest. It is working great 👍

Maybe this advice should be put in the readme. At the moment it suggests to deploy on vercel as is:

> We chose to make this example with NextJS so that you can run one command to get the API running, and also so that you could deploy this to Vercel to load updates from a real server. If you choose to deploy this to Vercel, you'll need to find the URL the endpoints exist at, then update the Expo.plist for iOS with the URL under the EXUpdatesURL key, then rebuild a "release" app to include the new URL.

**Comment by vlimag** [comment]
@denniske would you give examples on how you doing that?
Actually for me even the update with one single update batch wasnt working.

So atm Im hosting into a EC2 server (where S3 files are populating the server every minute with eventual updates)

**Comment by denniske** [comment]
@vlimag see this repo https://github.com/denniske/aoe2companion-update

**Comment by wschurman** [comment]
This repo serves as a basic demonstration. Asset hosting is definitely something that needs to be architected and built out for a production implementation of the protocol.
