### ISSUE TITLE
updates.scope_key, updates.commit_time (code 2067 SQLITE_CONSTRAINT_UNIQUE)

### ISSUE THREAD

**Issue by laxyloginext** [expo/custom-expo-updates-server#47]
Hi, I am getting this error in Android Studio logcat when I remove the app from the background and open it again to get the update.

Response i am getting before the error:  {"timestamp":1715865979617,"message":"Updates state change: DownloadError, context = {isUpdateAvailable=true, isUpdatePending=false, isChecking=false, isDownloading=false, isRestarting=false, latestManifest={\"id\":\"4edb39fa-f8e1-86d2-f524-0252da0a4e89\",\"createdAt\":\"2024-05-16T13:07:39.792Z\",\"runtimeVersion\":\"1\",\"assets\":[{\"hash\":\"JCcs2u_4LMX6zazNmCpvBbYMRQRwS7-UwZpjiGWYgLs\",\"key\":\"4f1cb2cac2370cd5050681232e8575a8\",\"fileExtension\":\".png\",\"contentType\":\"image\\\/png\",\"url\":\"http:\\\/\\\/localhost:3000\\\/api\\\/assets?asset=updates\\\/1\\\/1715864830\\\/assets\\\/4f1cb2cac2370cd5050681232e8575a8&runtimeVersion=1&platform=android\"}],\"launchAsset\":{\"hash\":\"DZD2QJ_xs4cPyM2dIba3aU91jCDFVlyjMgOlYoxn-HM\",\"key\":\"325f402ac678fd3a8e5753d8ba3e616e\",\"fileExtension\":\".bundle\",\"contentType\":\"application\\\/javascript\",\"url\":\"http:\\\/\\\/localhost:3000\\\/api\\\/assets?asset=updates\\\/1\\\/1715864830\\\/bundle\\\/index-31f4eb9880cab5f0618f9b9bf660a7d7.hbc&runtimeVersion=1&platform=android\"},\"metadata\":{},\"extra\":{\"expoClient\":{\"name\":\"expo-updates-client\",\"slug\":\"expo-updates-client\",\"owner\":\"anonymous\",\"version\":\"1.0.0\",\"orientation\":\"portrait\",\"icon\":\".\\\/assets\\\/icon.png\",\"splash\":{\"image\":\".\\\/assets\\\/splash.png\",\"resizeMode\":\"contain\",\"backgroundColor\":\"#ffffff\"},\"runtimeVersion\":\"1\",\"updates\":{\"url\":\"http:\\\/\\\/192.168.0.101:3000\\\/api\\\/manifest\",\"enabled\":true,\"fallbackToCacheTimeout\":30000,\"codeSigningCertificate\":\".\\\/code-signing\\\/certificate.pem\",\"codeSigningMetadata\":{\"keyid\":\"main\",\"alg\":\"rsa-v1_5-sha256\"}},\"assetBundlePatterns\":[\"**\\\/*\"],\"ios\":{\"supportsTablet\":true,\"bundleIdentifier\":\"com.test.expo-updates-client\"},\"android\":{\"adaptiveIcon\":{\"foregroundImage\":\".\\\/assets\\\/adaptive-icon.png\",\"backgroundColor\":\"#FFFFFF\"},\"package\":\"com.test.expoupdatesclient\"},\"web\":{\"favicon\":\".\\\/assets\\\/favicon.png\"},\"sdkVersion\":\"47.0.0\",\"platforms\":[\"ios\",\"android\",\"web\"],\"currentFullName\":\"@anonymous\\\/expo-updates-client\",\"originalFullName\":\"@anonymous\\\/expo-updates-client\"}},\"isVerified\":true}, downloadError={message=UNIQUE constraint failed: updates.scope_key, updates.commit_time (code 2067 SQLITE_CONSTRAINT_UNIQUE)}, lastCheckForUpdateTime=Thu May 16 18:56:19 GMT+05:30 2024}","code":"None","level":"info"}

Error: Unexpected error encountered while loading this app android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: updates.scope_key, updates.commit_time (code 2067 SQLITE_CONSTRAINT_UNIQUE)

 

Steps I followed:

1. Download the repo
2. npm i in client/server side
3. Since I am testing this project locally I have changed the server address from http://localhost:3000/api/manifest to http://ip:3000/api/manifest address on the client side ( in androiManifest & app.json).
4. build the release with this command yarn android --variant release and install it into my physical device.
5. change the app.JSX content and export on the client side using this command => npx expo export 
6. and copy bundle/assets from dist folder ( which is located in dist/_expo/static/js/android/index-293872fh29f.hbc and assets file located in dist/assets/417631dh78e37hd137)
7. and paste into server side update folder ( Ex: 1(runtim
![Screenshot 2024-05-16 at 7 34 35 PM](https://github.com/expo/custom-expo-updates-server/assets/143159157/b0aae813-2abc-42c1-a90a-0df017489496)
e version)/1715867705(timestamp)/assets & bundle ) attaching ss for ref
8. npm run dev on the server side
9. I am getting an error when I open the app.
 
 
 Attaching app.json for ref:
[app.json](https://github.com/expo/custom-expo-updates-server/files/15336436/app.json)

Please let me know what went wrong here. I appreciate any help you can provide.

**Comment by yadavmurari111** [comment]
I am also experiencing same issue

**Comment by laxyloginext** [comment]
The issue has been resolved. I was mistakenly using a .js bundle in update/1/timestamp/metadata.json instead of the correct .hbc extension. Additionally, make sure to update the expo-update-server HOSTNAME URL to your PC's IP address. This change ensures that the correct URL is used to download assets on your physical device.
