### ISSUE TITLE
[INFO] Why "force reload" to just check for updates ?

### ISSUE THREAD

**Issue by nouri-soirees** [expo/custom-expo-updates-server#54]
In the documentation `README` of this repo, "how expo updates works" [section](https://github.com/expo/custom-expo-updates-server?tab=readme-ov-file#how-the-expo-update-server-works) is there a reason to force close and reopen the app just to make the request ? I noticed this in the expo-updates package (from expo not from this repo) ?

Why not check for the update and then decide ? Is it really necessary to force reload the JS just to check if there is an update ?
Just by enabling the expo-updates (from the supported files for ios and android) I noticed this "force reload" just as the app loads.

> In the "release" app, force close and reopen the app to make a request for an update from the custom update server. The server will return a manifest that matches the requests platform and runtime version.

**Comment by wschurman** [comment]
This repo is a demonstration of a basic potential example setup. See the expo-updates docs for more info on configuration. https://docs.expo.dev/versions/latest/sdk/updates/
