### ISSUE TITLE
Is this repository still being maintained? I would like to know if it can still be used with the latest version of Expo.

### ISSUE THREAD

**Issue by baichen99** [expo/custom-expo-updates-server#55]
"I encountered the same issue as described in this  https://stackoverflow.com/questions/75531223/expo-updates-failed-to-download-new-update

**Comment by keshavoh** [comment]
Yep, working perfectly on latest sdk as well. The next code needs to be tweaked here and there which took me a while, envs, and the commands had to be tweaked to fit my usecase.

If nothing specific, you can go ahead without it as well.

**Comment by wschurman** [comment]
Updated the readme with a note about warranty and support for this repo.
